### PR TITLE
Update statistics data provider support

### PR DESCRIPTION
**Pull request by bhufmann**

### CODE REVIEW

**Comment by bhufmann** [comment]
To test with Trace Compass server use the following patches:
- Trace Compass (4 chain of patches): https://git.eclipse.org/r/#/c/163897/ 
- Trace Compass incubator: https://git.eclipse.org/r/#/c/165316/

**Comment by bhufmann** [comment]
> To test with Trace Compass server use the following patches:
> 
>     * Trace Compass (4 chain of patches): https://git.eclipse.org/r/#/c/163897/
> 
>     * Trace Compass incubator: https://git.eclipse.org/r/#/c/165316/
The incubator patch has been merged. 
New Trace Compass patches are needed. Use following one and dependent patches: 
https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/165900/2

**Comment by bhufmann** [comment]
Works with Trace Compass master of today.

**Comment by MatthewKhouzam** [comment]
`╒═══════════════════════════╤═══════════╤════════════╤═══════════╤═══════════╤═════════╤════════════╕
│ Label                     │ Minimum   │ Maximum    │ Average   │ Std Dev   │   Count │ Total      │
╞═══════════════════════════╪═══════════╪════════════╪═══════════╪═══════════╪═════════╪════════════╡
│ k                         │ 1.086 µs  │ 137.483 µs │ 19.72 µs  │ 16.657 µs │   19725 │ 388.968 ms │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ |____Total                │ 1.086 µs  │ 137.483 µs │ 19.72 µs  │ 16.657 µs │   19725 │ 388.968 ms │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ | |____radeon             │ 7.75 µs   │ 9.353 µs   │ 8.552 µs  │ ---       │       2 │ 17.103 µs  │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ | |____i915               │ 7.444 µs  │ 83.309 µs  │ 30.469 µs │ 10.453 µs │    9327 │ 284.183 ms │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ | |____eno1               │ 1.086 µs  │ 22.096 µs  │ 4.208 µs  │ 3.396 µs  │    1173 │ 4.935 ms   │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ | |____acpi               │ 57.119 µs │ 94.024 µs  │ 72.153 µs │ 10.475 µs │      19 │ 1.371 ms   │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ | |____xhci_hcd           │ 22.961 µs │ 137.483 µs │ 50.489 µs │ 18.449 µs │    1038 │ 52.407 ms  │
├───────────────────────────┼───────────┼────────────┼───────────┼───────────┼─────────┼────────────┤
│ | |____ahci[0000:00:1f.2] │ 2.173 µs  │ 40.091 µs  │ 5.64 µs   │ 2.954 µs  │    8166 │ 46.055 ms  │
╘═══════════════════════════╧═══════════╧════════════╧═══════════╧═══════════╧═════════╧════════════╛`
Doees it paste well?

**Comment by bhufmann** [comment]
unfortunately no
________________________________

**Comment by MatthewKhouzam** [comment]
with `<pre>` it does

**Comment by bhufmann** [comment]
In text based emails probably too.
Bernd
________________________________

**Comment by bhufmann** [comment]
Thanks for the review

**Pull request merged**
