### PR TITLE
Increase pytest coverage by either adding tests or removing unused code

### PR DESCRIPTION
**Pull request by marco-miller**
- Add a completed `timegraph` tree test in `TestTspClient`.
- Remove the unused `DataType` class with its whole file.
- Remove the redundant local variable in `EntryModel`.
- Move `Tree{Model,Item}` out of the `tsp` package, being `cli` only.
- Add `pragma`s where there is no pytest coverage necessary yet.

### CODE REVIEW

**Comment by marco-miller** [comment]
My latest force-push (diff linked above) here only rebased this PR on #28, still per description at top above.

**Comment by marco-miller** [comment]
Per this PR description at top, this PR is based on #28, so this specific review starts with e652dbb included (then up).

**Comment by marco-miller** [comment]
My very latest force-push only rebased this PR on current latest #28. So this PR now starts with 
ac2fe21 and up (7 commits total, here).

**Comment by marco-miller** [comment]
@MatthewKhouzam and @bhufmann, this PR contains only its own diffs now, ready for your review; thanks.

**Comment by bhufmann** [comment]
> @MatthewKhouzam and @bhufmann, this PR contains only its own diffs now, ready for your review; thanks.

@marco-miller The code looks good to me. I'm ok to remove the parsing and storing of the unspecified parameters in field 'others' (according to #35). For the removal "DataType", I think for now it's ok to remove it, and it can be added (or something similar) back once there is a way forward for https://github.com/theia-ide/trace-server-protocol/pull/50.

The PR message however, doesn't fully reflect all the changes done in this PR. Could you please give a brief summary in the PR description?

**Comment by marco-miller** [comment]
> @marco-miller The code looks good to me. I'm ok to remove the parsing and storing of the unspecified parameters in field 'others' (according to #35). For the removal "DataType", I think for now it's ok to remove it, and it can be added (or something similar) back once there is a way forward for [theia-ide/trace-server-protocol#50](https://github.com/theia-ide/trace-server-protocol/pull/50).

Ack. Thanks for the review.

> The PR message however, doesn't fully reflect all the changes done in this PR. Could you please give a brief summary in the PR description?

Done; thanks.

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
